# stream
# VIDEO_SOURCE = 'http://nyn_cam:Means1122@144.122.181.48:8080/video'
# VIDEO_SOURCE = 1
VIDEO_SOURCE = 0
VIEW_MODE = False

# serial
SERIAL_ON = False
SERIAL_PORT = '/dev/ttyUSB0'
SERIAL_BAUDRATE = 9600
ARDUINO_RESPONSE_ON = False

# agent
TURN_TOLERANCE = 50 # pixels
QR_ENABLED = True
CONTOUR_ENABLED = False
MIDP_ENABLED = False
KNN_ENABLED = False
REFERENCE_IMG_PATH = 'ref_img/sekil_ref.jpg'

# calibration
FOCAL_LENGTH = 491.54655888988026
CALIBRATE_MODE = True
CALIBRATE_MODE_TRIAL_COUNT = 10
QR_LENGTH = 16.5
OBJ_LENGTH = 19

# misc
FPS_ON = True
NO_FRAME_FPS_ON = False
